#! /usr/bin/env bash

delete_local_tags

delete_local_tags() {
    git tag -d $(git tag -l)
}

delete_remote_tags() {
    git push origin --delete $(git tag -l)
}

delete_all_tags() {
    delete_local_tags
    git fetch
    delete_remote_tags
    delete_local_tags
}
