#!/usr/bin/env bash

git checkout main
git pull

VERSION=$(python3 -c "from src.pyrob import __version__; print(__version__)")
TAG=v$VERSION

git tag -a $TAG -m "release $VERSION"

if [ $? -eq 0 ]; then
  git push origin $TAG
else
  echo error: failed to tag build
fi
